[package]
name = "ood-mailer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-gmail1 = "5.0.2+20230116"
tokio = { version = "1.28.1", features = ["full"] }
